Adding Metadata and Download Script
walkway-project/utils pull request #1
Opened 2023-09-15 00:45 UTC by echavemann

2023-09-15 03:28 UTC, jiale0402 requested changes

2023-09-15 03:28 UTC, jiale0402 commented on DataFetching/metadata/metadata.py
Need to have start&end time specified as well, +maybe granularity (l2)?

2023-09-15 16:49 UTC, echavemann commented on DataFetching/metadata/metadata.py
why

2023-09-15 16:50 UTC, echavemann commented on DataFetching/metadata/metadata.py
start and end yea granularity i think no need

2023-09-15 16:56 UTC, echavemann commented on DataFetching/metadata/metadata.py
ill add an enum lamo

2023-09-15 17:01 UTC, jiale0402 commented on DataFetching/metadata/metadata.py
How are we preventing unnecessary downloading if we don’t even know shit about what’s in the json lmao + wrangler needs to know start & end of data instead of throwing random errors

2023-09-15 17:02 UTC, jiale0402 commented on DataFetching/metadata/metadata.py
Ideally we even need the shape of data for indexing

2023-09-15 17:05 UTC, jiale0402 commented on DataFetching/metadata/metadata.py
We currently dont have date range specified for wrangler because all the infra assumed we will only ask it to compute features between start of and 2021 and end of 2022

2023-09-15 17:25 UTC, echavemann commented on DataFetching/metadata/metadata.py
granularity doesnt matter
we arent getting new data anytime soon xd

2023-09-15 17:25 UTC, echavemann commented on DataFetching/metadata/metadata.py
i agrred earlier that we should add timeframe

2023-09-15 17:26 UTC, echavemann commented on DataFetching/metadata/metadata.py
> Ideally we even need the shape of data for indexing
why

2023-09-15 17:35 UTC, jiale0402 commented on DataFetching/metadata/metadata.py
> Ideally we even need the shape of data for indexing
> why

Some time in the future we will see data that don’t come up in same freq and data that don’t start or end as other data that we are using if we intend to dig more features, w/o start and end and schema (shape) there’s no way our backtester/wrangler work with those data simultaneously

2023-09-15 17:38 UTC, echavemann commented on DataFetching/metadata/metadata.py
it has start and end and the schema is literally our own, i see no reason to add this to md

2023-09-15 17:38 UTC, echavemann commented on DataFetching/metadata/metadata.py
dont we have headers anyway

2023-09-15 17:39 UTC, echavemann commented on DataFetching/metadata/metadata.py
again this is downloads not features

2023-09-15 17:40 UTC, echavemann commented on DataFetching/metadata/metadata.py
also this scheme guarantees all data starts and ends at same time bc it is all batched together

2023-09-15 17:40 UTC, echavemann commented on DataFetching/metadata/metadata.py
> also this scheme guarantees all data starts and ends at same time bc it is all batched together

at least as far as tardis can give us

2023-09-16 15:13 UTC, echavemann commented
@jiale0402 this is blocking, please review

2023-09-16 15:23 UTC, echavemann commented
Approved via WeChat DM 9/16 10:20AM

2023-09-16 15:23 UTC, merged